coolsite/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import BasketModelViewSet, ProductModelViewSet

router = DefaultRouter()
router.register(r"products", ProductModelViewSet)
router.register(r"baskets", BasketModelViewSet)

urlpatterns = [
   path('', include(router.urls))
]

coolsite/coolsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from coolsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('', include('userss.urls')),
    path('api/', include('api.urls')),
    path('api-token-auth/', obtain_auth_token),
    path("__debug__/", include("debug_toolbar.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coolsite/product/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from product.views import (AboutUs, Baskets, ContactView, HomeView, Order,
                           ProductDetail, Success, Tags, basket_add,
                           basket_delete, basket_remove, comment_add)

urlpatterns = [
    path('', cache_page(3)(HomeView.as_view()), name='home'),
    path('product/<slug:product_slug>/', ProductDetail.as_view(), name='product'),
    path('tag/<slug:tag_slug>/', Tags.as_view(), name='tags'),
    path('basket_add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket_remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('basket_delete/<int:basket_id>/', basket_delete, name='basket_delete'),
    path('basket/', Baskets.as_view(), name='baskets'),
    path('order/', Order.as_view(), name='order'),
    path('about_us/', AboutUs.as_view(), name='about_us'),
    path('comment/<int:product_id>/', comment_add, name='comment_add'),
    path('success/', Success.as_view(), name='success'),
    path('contact/', ContactView.as_view(), name='contact'),
]

coolsite/product/models.py
from django.db import models
from django.urls import reverse

from coolsite.settings import AUTH_USER_MODEL

# Create your models here.


class Product(models.Model):
    title = models.CharField(max_length=156, verbose_name='Наименование')
    slug = models.SlugField(unique=True, db_index=True, null=True, verbose_name='Слаг')
    price = models.DecimalField(max_digits=8, decimal_places=2, null=True, verbose_name='Стоимость')
    quantity = models.PositiveIntegerField(default=0, null=True)
    content = models.TextField(verbose_name='Описание')
    time_created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='products', verbose_name='Фото', null=True, blank=True)
    tags = models.ManyToManyField('Tag', verbose_name='Теги')
    is_published = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Продукты'
        ordering = ('-id',)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('product', kwargs={'product_slug': self.slug})


class Tag(models.Model):
    title = models.CharField(max_length=156, verbose_name='Наименование тега')
    slug = models.SlugField(db_index=True, unique=True)

    class Meta:
        verbose_name = 'Ингридиенты'
        ordering = ('-id',)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('tags', kwargs={'tag_slug': self.slug})


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(null=True)
    time_created = models.DateTimeField(auto_now_add=True)
    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = 'Корзина'

    def __str__(self):
        return f"Корзина {self.product}"

    def sum(self):
        return self.product.price * self.quantity


class Comment(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_query_name='user')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField(verbose_name='Комментарий')

    class Meta:
        verbose_name = 'Комментарии'
        ordering = ('-id',)

    def __str__(self):
        return f"Комментарий пользователя {self.user}"


class ProductShots(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_shots', null=True)

    class Meta:
        verbose_name = 'Фото'
        ordering = ('-id',)

    def __str__(self):
        return f"Картинка для {self.product}"


class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=50)

    def __str__(self):
        return self.name

coolsite/product/forms.py
from django import forms

from product.models import Comment, Contact


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='Ваш комментарий: ', widget=forms.Textarea(attrs={'cols': 68, 'rows': 5}))

    class Meta:
        model = Comment
        fields = ('content', )


class ContactForm(forms.ModelForm):
    name = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Contact
        fields = ('name', 'email')

coolsite/product/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic import CreateView, DetailView, ListView, TemplateView

from product.forms import CommentForm, ContactForm
from product.models import Basket, Comment, Contact, Product
from product.tasks import send_spam_email
from product.utils import DataMixin

# Create your views here.


class HomeView(DataMixin, ListView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(is_published=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HomeView, self).get_context_data()
        c_def = self.get_user_context(title='STORE - Каталог')
        return dict(list(context.items())+list(c_def.items()))


def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    basket = Basket.objects.filter(user=request.user, product=product)

    if not basket.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = basket.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)

    basket.quantity -= 1
    basket.save()

    if basket.quantity == 0:
        basket.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_delete(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class ProductDetail(DataMixin, DetailView):
    model = Product
    template_name = 'product/product_detail.html'
    context_object_name = 'product'
    slug_url_kwarg = 'product_slug'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetail, self).get_context_data()
        c_def = self.get_user_context(title=context['product'])
        return dict(list(context.items())+list(c_def.items()))


class Tags(DataMixin, ListView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(tags__slug=self.kwargs['tag_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Tags, self).get_context_data()
        c_def = self.get_user_context(title='STORE - Каталог')
        return dict(list(context.items())+list(c_def.items()))


class Order(DataMixin, ListView):
    model = Basket
    context_object_name = 'baskets'
    template_name = 'product/order.html'

    def get_queryset(self):
        return Basket.objects.all().select_related('user')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Order, self).get_context_data()
        c_def = self.get_user_context(title='Только для администратора')
        return dict(list(context.items())+list(c_def.items()))


class AboutUs(DataMixin, TemplateView):
    template_name = 'product/about_us.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(AboutUs, self).get_context_data()
        c_def = self.get_user_context(title='Информация о нас')
        return dict(list(context.items())+list(c_def.items()))


class Success(DataMixin, TemplateView):
    template_name = 'product/success.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Success, self).get_context_data()
        c_def = self.get_user_context(title='Поздравляем')
        return dict(list(context.items())+list(c_def.items()))


class Baskets(DataMixin, ListView):
    model = Basket
    template_name = 'product/basket.html'
    context_object_name = 'baskets'

    def get_queryset(self):
        return Basket.objects.filter(user=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Baskets, self).get_context_data()
        c_def = self.get_user_context(title='Корзина')
        return dict(list(context.items())+list(c_def.items()))


def comment_add(request, product_id):
    product = Product.objects.get(id=product_id)
    comment = Comment.objects.filter(product=product)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.product = product
            form.save()
            return redirect(comment_add, product_id)
    else:
        form = CommentForm()

    return render(request, 'product/comments.html', {
        'product': product,
        'comment': comment,
        'form': form,
    })


class ContactView(DataMixin, CreateView):
    model = Contact
    form_class = ContactForm
    success_url = '/'
    template_name = 'product/contact.html'

    def form_valid(self, form):
        form.save()
        send_spam_email.delay(form.instance.email)
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ContactView, self).get_context_data()
        c_def = self.get_user_context(title='Оповестите пользователя о наших новинках!')
        return dict(list(context.items())+list(c_def.items()))

coolsite/product/templates/product/about_us.html
{% extends 'product/base.html' %}

{% block content %}
<br>
<br>
<br>
<div class="card">
  <div class="card-body">
      <h3>Это приложение является социальной сетью с интернет-магазином доставки суш,
          где у каждого пользователя есть возможность не только совершить заказ,а еще и
          создать личный кабинет,высказать свое мнение в комментариях о каждом блюде,и вести участие
          в дискусировании новый блюд!
      </h3>
  </div>
</div>




{% endblock %}

coolsite/product/templates/product/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% load static %}
    {% load humanize %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
</head>
<body>


<!-- Шапка сайта -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">SUSHI CLUB MASTER</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">


<li class="nav-item">
    <a class="nav-link" href="{% url 'about_us' %}">О нас</a>
</li>


<div class="navbar-nav ml-auto">
    <div class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ингридиенты <i class="fa-solid fa-paperclip"></i>
       </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">

{% for tag in tags %}
         <a class="dropdown-item" href="{{ tag.get_absolute_url }}">#{{ tag.title }}</a>
{% endfor %}
       </div>
     </div>
</div>


{% if user.is_superuser %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'order' %}">Заказы</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'contact' %}">Связаться с покупателем</a>
</li>
{% endif %}
      </ul>

    </div>
{% if request.user.is_authenticated %}

<div class="navbar-nav mx-auto">
    <div class="nav-item dropdown ">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {% if user.image %}
              <img width="50" src="{{ user.image.url }}" class="mr-3 rounded-circle" alt="Please,download your photo">
          {% else %}
              <i class="fa-regular fa-user"></i>
          {% endif %}
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'update_profile' %}">Личный кабинет<i class="fa-solid fa-user-pen"></i></a>

        <a class="dropdown-item" href="{% url 'baskets' %}">Корзина<i class="fa-solid fa-basket-shopping"></i></a>

        <a class="dropdown-item" href="{% url 'logout_user' %}">Выход<i class="fa-solid fa-person-running"></i></a>
      </div>
    </div>
</div>
      <div class="navbar-nav mx-auto">Добро пожаловать,{{ user.first_name }} !  </div>
{% else %}

<a type="button" class="btn btn-light" href="{% url 'register' %}">Регистрация</a><a type="button" class="btn btn-light" href="{% url 'login' %}">Вход</a>

{% endif %}
  </nav>

{% block content %}
{% endblock %}

{% if page_obj.has_other_pages %}
<nav aria-label="...">
  <ul class="pagination">
{% if page_obj.has_previous %}
    <li class="page-item">
      <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&lt;</a>
    </li>
{% endif %}
{% for p in paginator.page_range %}
    {% if page_obj.number == p %}
          <li class="page-item active" aria-current="page">
              <a class="page-link" href="#">{{ p }}</a>
          </li>
    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
      <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
    {% endif %}
{% endfor %}
{% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a>
    </li>
{% endif %}
  </ul>
</nav>
{% endif %}

  <!-- Подвал сайта -->
  <footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <span class="text-muted">© 2024 Название магазина</span>
    </div>
  </footer>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>



</body>
</html>

coolsite/product/templates/product/basket.html
{% extends 'product/base.html' %}

{% block content %}

{% if baskets %}
<br>
<table class="table">
  <h3 class="text-center">{{ title }}</h3>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Фото</th>
      <th scope="col">Наименование</th>
      <th scope="col">Цена за еденицу</th>
      <th scope="col">Колл-во</th>
    </tr>
  </thead>
  <tbody>
{% for basket in baskets %}
    <tr>
      <th scope="row">{{ basket.product.pk }}</th>
      <td><img width="50px" src="{{ basket.product.image.url }}" class="rounded float-start" alt="..."></td>
      <td>{{ basket.product.title }}</td>
      <td>{{ basket.product.price }}$</td>
      <td><a href="{% url 'basket_remove' basket.id %}">-</a> {{ basket.quantity }} <a href="{% url 'basket_add' basket.product.id %}">+</a></td>
      <td><a href="{% url 'basket_delete' basket.id %}"><i class="fa-solid fa-trash"></i></a></td>
    </tr>
{% endfor %}
  </tbody>
</table>
<h3>Итого: {{ baskets.total_sum }}</h3>
<a href="{% url 'success' %}">Оформить заказ</a>
{% else %}
<h5 class="card-title text-center">Корзина пока что пуста</h5>
{% endif %}
{% endblock %}

coolsite/product/templates/product/comments.html
{% extends 'product/base.html' %}

{% block content %}

 <!-- Форма добавления комментария -->

<br>
<h3 class="card-title text-center">Выскажите свое мнение о {{ product }} !</h3>
<br>
    <form method="post">
      <div class="form-group">
         {% csrf_token %}
          {% if user.image %}
             <img width="35" src="{{ user.image.url }}" class="mr-3 rounded-circle">
          {% else %}
             <i class="fa-regular fa-user"></i>
          {% endif %}
         {% for f in form %}
         <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }} </label>{{ f }}
         {% endfor %}
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </form>

    <hr>

    <!-- Список комментариев -->
    <div class="comments">
      <!-- Пример одного комментария -->
      <div class="media mb-4">
          {% for c in product.comment_set.all %}
        <div class="media-body">
        {% if c.user.image %}
             <img width="35" src="{{ c.user.image.url }}" class="mr-3 rounded-circle" alt="Аватар">
        {% else %}
             <i class="fa-regular fa-user"></i>
        {% endif %}
          <h5 class="mt-0">@{{ c.user.username }}</h5>
            <p>{{ c.content }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <small></small>
          </div>
            <hr>
        </div>
          {% endfor %}
      </div>
    </div>

{% endblock %}

coolsite/product/templates/product/contact.html
{% extends 'product/base.html' %}

{% block content %}

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title text-center">{{ title }}</h5>
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'contact' %}">
            <div class="form-group">
                <br>
               {% csrf_token %}
               <div class="form-error">{{ form.non_field_errors }}</div>
               {% for f in form %}
               <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }} </label>{{ f }}
               <div class="form-error">{{ f.errors }}</div>
               {% endfor %}
            </div>
              <br>
            <button type="submit" class="btn btn-primary btn-block">Обновить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

coolsite/product/templates/product/index.html
{% extends 'product/base.html' %}
{% load cache %}

{% block content %}

  <!-- Контент сайта -->
  <div class="container mt-5">
    <h2>{{ title }}</h2>
    <div class="row">
      <!-- Пример карточки товара -->

  {% for product in products %}
      <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
        <div class="card">
{% if product.image %}
          <img width="240px" height="200px" src="{{ product.image.url }}" class="rounded mx-auto d-block" alt="Товар">
{% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ product.title }}</h5>
            <p class="card-text">{{ product.content|truncatewords:8 }}</p>
            <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Перейти</a>
              <br>
          {% if request.user.is_authenticated %}
             <a href="{% url 'comment_add' product.id %}">Комментировать  <i class="fa-regular fa-comment"></i></a>
          {% else %}
              <a href="{% url 'login' %}">Комментировать  <i class="fa-regular fa-comment"></i></a>
          {% endif %}
          </div>
        </div>
      </div>
  {% endfor %}

      <!-- Конец примера карточки товара -->
      <!-- Здесь могут быть добавлены другие карточки товаров -->
    </div>
  </div>

{% endblock %}

coolsite/product/templates/product/order.html
{% extends 'product/base.html' %}

{% block content %}

{% if baskets %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">№ заказа</th>
      <th scope="col">Фото</th>
      <th scope="col">Заказчик</th>
      <th scope="col">Адрес доставки</th>
      <th scope="col">Наименование</th>
      <th scope="col">Колл-во</th>
      <th scope="col">Сумма заказа</th>
    </tr>
  </thead>
  <tbody>
{% for b in baskets %}
    <tr>
      <th scope="row">№{{ b.user.id }}</th>
      <td><img width="50px" src="{{ b.product.image.url }}" class="rounded float-start" alt="..."></td>
      <td>{{ b.user.first_name }}</td>
      <td>{{ b.user.address }}</td>
      <td>{{ b.product.title }}</td>
      <td>{{ b.quantity }}</td>
      <td>{{ b.sum }}$</td>
      <td><a href="{% url 'basket_delete' b.id %}"><i class="fa-solid fa-trash"></i></a></td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% else %}
<h5 class="card-title text-center">Заказов пока что нет</h5>
{% endif %}

{% endblock %}

coolsite/product/templates/product/product_detail.html
{% extends 'product/base.html' %}

{% block content %}

  <!-- Контент страницы -->
  <div class="container mt-5">
    <div class="row">
      <div class="col-lg-6">
{% if product.image %}
        <img width='400px' height="350" src="{{ product.image.url }}" class="rounded" alt="Товар">
{% endif %}
<br>
<br>
{% for image in product.productshots_set.all %}
        {% if image.image %}
           <img width="200px" height="150" src="{{ image.image.url }}" class="rounded" alt="...">
        {% endif %}
{% endfor %}
      </div>

      <div class="col-lg-6">
        <h2>{{ product.title }}</h2>
        <br>
        Основные ингридиенты:
{% for t in product.tags.all %}
        <h5><a href="{{ t.get_absolute_url }}">#{{ t.title }}</a></h5>
{% endfor %}
        <br>
        <p>{{ product.content }}</p>
        <p><strong>Цена:</strong>{{ product.price }}$</p>
        {% if request.user.is_authenticated %}
          <a href="{% url 'basket_add' product.id %}" class="btn btn-primary">Добавить в корзину</a></button>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-primary">Добавить в корзину</a></button>
        {% endif %}
      </div>
    </div>
  </div>


{% endblock %}

coolsite/product/templates/product/success.html
{% extends 'product/base.html' %}

{% block content %}


<div class="card-body">
                      <div class="wrapper text-center">
                        <h4 class="card-title">Заказ оформлен!</h4>
                        <p class="card-description">В течении 3-х минут с вами свяжеться администратор по вашему EMAIL.<br>
                            Если ваш EMAIL устарел,то поменяйте его <a href="{% url 'update_profile' %}">ЗДЕСЬ</a></p>
                        <a href="{% url 'home' %}"><button class="btn btn-outline-success"onclick="showSwal('success-message')">Домой</button></a>
                      </div>
</div>

{% endblock %}